### ISSUE TITLE
Consul Service Discovery

### ISSUE THREAD

**Issue by mhotan** [socrata/shipyard#24]
Add script that has the ability to query the local host consul agent and return services of a given name.

IE.
Define a python script named something like consul_service that does

export ZOOKEEPERS = $(consul_service "zookeeper")
echo $ZOOKEEPERS 

> > 10.0.0.1:2181,10.0.0.2:2181

**Comment by nmeyerhans** [comment]
I agree that we should provide a wrapper around consul. I'd add a couple of points:

1. It should not query consul synchronously. Instead it should read from a cache that is asynchronously updated, similar to [Eureka from netflix](https://github.com/Netflix/eureka).

2. The usage example given, involving environment variables, is not an ideal pattern for this. Since environment variables are only inherited by children at exec(), the processes don't have any way of learning about changes to the values returned by consul. IMO we'd be better off implementing small libraries in our commonly used languages that provide functions for learning about the current consul values.

**Comment by znep** [comment]
1. Isn't this what https://github.com/hashicorp/envconsul is supposed to do?

2. I'm not convinced consul is a good way to get information about things like zookeeper.  It gives a list of services currently up and registered, not a complete list of nodes that we know should exist.  This rapidly falls apart under various failure scenarios, eg. rolling reboots.

**Comment by mhotan** [comment]
@nmeyerhans Agreed a better solution is to have folks introduce the ability to use Consul for Service discovery at the application level.  I was looking for a more short term "step in the right direction" fix.  I have faced counter arguments about introducing consul into our projects as a dependency.  

@znep I believe that envconsul just simply translated Key values to environment variables for child processes.  They have yet to build in the consul agent or catalog feature set.  I think the correct solution if we went this route would be to extend their current feature set.
